export default{
    products: [
        {
            _id:'1',
            name:'Full Shirt 1',
            category:'Shirts',
            image:'/images/product-1.jpg',
            price:60,
            brand:'Hiskywin',
            rating:4.5,
            numReviews:10,
            countInStock:6,
        },
        {
            _id:'2',
            name:'Full Shirt 2',
            category:'Shirts',
            image:'/images/product-2.jpg',
            price:55,
            brand:'Nike',
            rating:4.2,
            numReviews:14,
            countInStock:6,
        },
        {
            _id:'3',
            name:'Full Shirt 3',
            category:'Shirts',
            image:'/images/product-3.jpg',
            price:62,
            brand:'Adidas',
            rating:4.5,
            numReviews:40,
            countInStock:10,
        },
        {
            _id:'4',
            name:'Jogging Pants 1',
            category:'Pants',
            image:'/images/product-4.jpg',
            price:85,
            brand:'Hiskywin',
            rating:4.8,
            numReviews:90,
            countInStock:22,
        },
        {
            _id:'5',
            name:'Jogging Pants 2',
            category:'Pants',
            image:'/images/product-5.jpeg',
            price:80,
            brand:'Nike',
            rating:4.2,
            numReviews:30,
            countInStock:3,
        },
        {
            _id:'6',
            name:'Jogging Pants 3',
            category:'Pants',
            image:'/images/product-6.jpeg',
            price:70,
            brand:'Adidas',
            rating:4.5,
            numReviews:55,
            countInStock:10,
        },
    ],
}